# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "test-env"
client_id = "fc663af6d92187d432b5cd7866870682"
application_url = "https://f4ed-187-11-39-232.ngrok-free.app"
embedded = false

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://f4ed-187-11-39-232.ngrok-free.app/auth/callback",
  "https://f4ed-187-11-39-232.ngrok-free.app/auth/shopify/callback",
  "https://f4ed-187-11-39-232.ngrok-free.app/api/auth/callback",
  "https://f4ed-187-11-39-232.ngrok-free.app/api/auth/offline",
  "https://f4ed-187-11-39-232.ngrok-free.app/api/auth/offline-callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
